# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nmp_8_VQkXR1lhRzP-sG7Eo8YlBhiq3E
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('/content/first inten project.csv')
data.head()

plt.figure(figsize=(10, 6))
sns.histplot(data['average price '], bins=30, kde=True)

# Set labels and title
plt.xlabel('Requests')
plt.ylabel('Numbers')
plt.title('No. Of the special requests')

# Show the plot
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='booking status', data=data)
plt.title('Booking Status Distribution')
plt.xlabel('Booking Status')
plt.show()

numeric_df = data.select_dtypes(include=['int64', 'float64'])
corr_matrix = numeric_df.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

sns.histplot(data=data, x='lead time', hue='booking status', bins=50, kde=True)
plt.title('Lead Time Distribution by Booking Status')
plt.xlabel('Lead Time')
plt.show()

sns.boxplot(x='booking status', y='special requests', data=data)
plt.title('Booking Status vs. Special Requests')
plt.xlabel('Booking Status')
plt.ylabel('Special Requests')
plt.show()

data['type of meal'].value_counts().plot(kind='bar')
plt.title('Most Common Meal Types')
plt.show()

data['market segment type'].value_counts().plot(kind='bar', color='green')
plt.title('Most Used Booking Channels (Online/Offline)')
plt.show()



plt.figure(figsize=(8, 5))
sns.countplot(x='special requests', data=data, palette='viridis')

plt.title('Number of Special Requests')
plt.xlabel('Special Requests')
plt.ylabel('Number of Bookings')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

data.isnull().sum()

data.info()

data.describe()



data['P-C'].value_counts()

data['P-not-C'].value_counts()

data['booking_status_encoded'] = data['booking status'].map({'Canceled': 1, 'Not_Canceled': 0})
import seaborn as sns
import matplotlib.pyplot as plt

numerical_features = ['lead time', 'special requests',
                      'number of adults', 'number of children',
                      'number of weekend nights', 'number of week nights','P-not-C','P-C','repeated']

for feature in numerical_features:
    plt.figure(figsize=(8, 5))
    sns.scatterplot(x=feature, y='booking_status_encoded', hue='booking status', data=data, palette='Set1')
    plt.title(f'{feature} vs Booking Status')
    plt.xlabel(feature)
    plt.ylabel('Booking Status (0 = Not Canceled, 1 = Canceled)')
    plt.tight_layout()
    plt.show()

print(data['booking status'].value_counts(normalize=True) * 100)

sns.countplot(data=data, x='booking status', palette='pastel')
plt.title('Booking Status Distribution')
plt.xlabel('Booking Status')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=data, x='booking status', y='lead time', palette='Set2')
plt.title('Lead Time by Booking Status')
plt.xlabel('Booking Status')
plt.ylabel('Lead Time (days)')
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(data=data, x='booking status', y='number of adults', ax=axes[0], palette='coolwarm')
axes[0].set_title('Adults vs Booking Status')

sns.boxplot(data=data, x='booking status', y='number of children', ax=axes[1], palette='coolwarm')
axes[1].set_title('Children vs Booking Status')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(data=data, x='type of meal', hue='booking status', palette='Set2')
plt.title('Meal Type vs Booking Status')
plt.xlabel('Meal Type')
plt.ylabel('Count')
plt.xticks(rotation=15)
plt.legend(title='Booking Status')
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(data=data, x='market segment type', hue='booking status', palette='Set1')
plt.title('Market Segment vs Booking Status')
plt.xlabel('Market Segment')
plt.ylabel('Count')
plt.xticks(rotation=15)
plt.legend(title='Booking Status')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=data, x='booking status', y = 'average price ', palette='coolwarm')
plt.title('Average Price by Booking Status')
plt.xlabel('Booking Status')
plt.ylabel('Average Price')
plt.show()

numerical_data = data.select_dtypes(include=['int64', 'float64'])

# Set figure size
plt.figure(figsize=(12, 8))

# Create correlation matrix
corr_matrix = numerical_data.corr()

# Plot heatmap
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)

# Title
plt.title("Correlation Heatmap of Numerical Features")
plt.tight_layout()
plt.show()



print(data.info())

data['average price '].unique()

data['P-C'].unique()

data['P-not-C'].unique()

data['booking status'].unique()

data['booking status']=data['booking status'].map({'Canceled':1,'Not_Canceled':0})

data['booking_status_encoded'].unique()

data['car parking space'].unique()

data['date of reservation'].unique()



data['lead time'].unique()

data['market segment type']=data['market segment type'].map({'Offline':0,'Online':1,'Corporate':2,'Aviation':3,'Complementary':4})

data['market segment type'].unique()

data['type of meal'].unique()

data['type of meal']=data['type of meal'].map({'Not Selected':0,'Meal Plan 1':1,'Meal Plan 2':2,'Meal Plan 3':3})

data['type of meal'].unique()

data['room type'].unique()

data['room type']=data['room type'].map({'Room_Type 1':1,'Room_Type 2':2,'Room_Type 3':3,'Room_Type 4':4,'Room_Type 5':5,'Room_Type 6':6,'Room_Type 7':7})

data['room type'].unique()

data.head()

data['date of reservation'].unique()

data['date of reservation'] = pd.to_datetime(data['date of reservation'], errors='coerce')

data['date of reservation'].isna().sum()
data['date of reservation'] = pd.to_datetime(data['date of reservation'])

data['date of reservation'].isna().sum()

data = data.dropna(subset=['date of reservation'])
data = data.drop('Booking_ID', axis=1)

data.head()

duplicates = data[data.duplicated()]
print(duplicates)

numerical_data = data.select_dtypes(include=['int64', 'float64'])

# Set figure size
plt.figure(figsize=(12, 8))

# Create correlation matrix
corr_matrix = numerical_data.corr()

# Plot heatmap
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)

# Title
plt.title("Correlation Heatmap of Numerical Features")
plt.tight_layout()
plt.show()

data['market segment type'].unique()

print(data.columns[data.columns.duplicated()])

data = data.loc[:, ~data.columns.duplicated()]

data = data.drop('booking_status_encoded', axis=1)

data.head()

data['date of reservation'] = pd.to_datetime(data['date of reservation'], errors='coerce')

# Drop rows with invalid or missing dates
data = data.dropna(subset=['date of reservation'])

# Create a new column with only year and month for grouping
data['month'] = data['date of reservation'].dt.to_period('M').astype(str)

# Group by month and count bookings
monthly_bookings = data.groupby('month').size()

# Convert index to datetime for plotting
monthly_bookings.index = pd.to_datetime(monthly_bookings.index)

# Plot
plt.figure(figsize=(12, 6))
sns.set(style="whitegrid")
plt.plot(monthly_bookings.index, monthly_bookings.values, marker='', color='blue', linewidth=2)
plt.title("The Most Monthly Booking")
plt.xlabel("Month")
plt.ylabel("No. Of bookings")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()